### ISSUE TITLE
ValueError: Sun does not reach altitude

### ISSUE THREAD

**Issue by hanifabd** [zainhussaini/salat#1]
halo brother, i got this error after the date is 19 May 2023

import salat
import datetime as dt
import pytz
from timezonefinder import TimezoneFinder

longitude = 106.18727177777018
latitude = -6.6432601

pt = salat.PrayerTimes(salat.CalculationMethod.MWL, salat.AsrMethod.STANDARD)

tfinder = TimezoneFinder()
timezone = pytz.timezone(tfinder.timezone_at(lng=longitude, lat=latitude))

date = dt.date(2023, 5, 22)

prayer_times = pt.calc_times(date, timezone, longitude, latitude)

print(prayer_times)

**Comment by zainhussaini** [comment]
Thanks for finding this! I went and created a new release that should fix this bug. Please let me know if you run into anything else!
